import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Carga de datos inicial para Fulbo:
 * - 32 Clubes categorizados con weights, baseMedia y tiers oficiales alineados a EA SPORTS FC 27.
 * - 352 Jugadores regulares (11 titulares por club en formación 4-3-3: 1 ARQ, 1 LI, 2 DFC, 1 LD, 2 MC, 1 MCO, 1 ED, 1 EL, 1 DC).
 * - Pool de 10 Leyendas/Ídolos históricos para eventos especiales.
 */
public final class DataLoader {

    private DataLoader() {
    }

    public static List<Club> createClubs() {
        return new ArrayList<>(Arrays.asList(
                new Club("River Plate", 10.0, 77.0, ClubTier.BUENO),
                new Club("Boca Juniors", 10.0, 77.0, ClubTier.BUENO),
                new Club("Racing Club", 8.0, 76.0, ClubTier.BUENO),
                new Club("Independiente", 7.0, 75.0, ClubTier.BUENO),
                new Club("Rosario Central", 7.5, 75.0, ClubTier.BUENO),
                new Club("Estudiantes LP", 7.0, 75.0, ClubTier.BUENO),
                new Club("Vélez Sarsfield", 7.0, 74.0, ClubTier.BUENO),
                new Club("Talleres de Córdoba", 7.0, 74.0, ClubTier.BUENO),
                new Club("Belgrano de Córdoba", 6.0, 74.0, ClubTier.INTERMEDIO),
                new Club("Lanús", 6.0, 74.0, ClubTier.INTERMEDIO),
                new Club("San Lorenzo", 6.0, 72.0, ClubTier.INTERMEDIO),
                new Club("Huracán", 6.0, 72.0, ClubTier.INTERMEDIO),
                new Club("Argentinos Juniors", 5.5, 72.0, ClubTier.INTERMEDIO),
                new Club("Platense", 5.0, 71.0, ClubTier.INTERMEDIO),
                new Club("Defensa y Justicia", 5.0, 71.0, ClubTier.INTERMEDIO),
                new Club("Atlético Tucumán", 4.5, 71.0, ClubTier.INTERMEDIO),
                new Club("Unión de Santa Fe", 4.5, 71.0, ClubTier.INTERMEDIO),
                new Club("Independiente Rivadavia", 4.5, 71.0, ClubTier.INTERMEDIO),
                new Club("Tigre", 4.5, 70.0, ClubTier.INTERMEDIO),
                new Club("Instituto de Córdoba", 4.5, 70.0, ClubTier.INTERMEDIO),
                new Club("Newell's Old Boys", 4.5, 70.0, ClubTier.INTERMEDIO),
                new Club("Central Córdoba (SdE)", 4.0, 69.0, ClubTier.INTERMEDIO),
                new Club("Barracas Central", 3.5, 69.0, ClubTier.MALO),
                new Club("Gimnasia LP", 4.0, 69.0, ClubTier.MALO),
                new Club("Gimnasia y Esgrima (M)", 3.5, 69.0, ClubTier.MALO),
                new Club("Banfield", 4.0, 68.0, ClubTier.MALO),
                new Club("Sarmiento de Junín", 3.5, 68.0, ClubTier.MALO),
                new Club("Deportivo Riestra", 3.5, 68.0, ClubTier.MALO),
                new Club("Aldosivi", 3.0, 67.0, ClubTier.MALO),
                new Club("Colón de Santa Fe", 3.5, 66.0, ClubTier.MALO),
                new Club("Estudiantes (RC)", 3.0, 65.0, ClubTier.MALO),
                new Club("Ferro Carril Oeste", 3.5, 65.0, ClubTier.MALO)
        ));
    }

    public static List<Player> createStandardPlayers() {
        return new ArrayList<>(Arrays.asList(
                // --- River Plate ---
                new Player("Santiago Beltrán", "River Plate", Position.ARQ, 72.0),
                new Player("Marcos Acuña", "River Plate", Position.LI, 77.0),
                new Player("Nicolás Otamendi", "River Plate", Position.DFC, 78.0),
                new Player("Lucas Martinez Quarta", "River Plate", Position.DFC, 76.0),
                new Player("Gonzalo Montiel", "River Plate", Position.LD, 77.0),
                new Player("Mauro Arambarri", "River Plate", Position.MC, 80.0),
                new Player("Aníbal Moreno", "River Plate", Position.MC, 78.0),
                new Player("Thiago Almada", "River Plate", Position.MCO, 78.0),
                new Player("Franco Mastantuono", "River Plate", Position.ED, 78.0),
                new Player("Angel Correa", "River Plate", Position.EL, 78.0),
                new Player("Sebastián Driussi", "River Plate", Position.DC, 77.0),
                // --- Boca Juniors ---
                new Player("Álvaro Montero", "Boca Juniors", Position.ARQ, 76.0),
                new Player("Lautaro Blanco", "Boca Juniors", Position.LI, 76.0),
                new Player("Marcos Rojo", "Boca Juniors", Position.DFC, 75.0),
                new Player("Lautaro Di Lollo", "Boca Juniors", Position.DFC, 76.0),
                new Player("Leandro Lozano", "Boca Juniors", Position.LD, 76.0),
                new Player("Leandro Paredes", "Boca Juniors", Position.MC, 81.0),
                new Player("Santiago Ascacíbar", "Boca Juniors", Position.MC, 77.0),
                new Player("Kevin Zenón", "Boca Juniors", Position.MCO, 78.0),
                new Player("Exequiel Zeballos", "Boca Juniors", Position.ED, 76.0),
                new Player("Sebastián Villa", "Boca Juniors", Position.EL, 77.0),
                new Player("Miguel Merentiel", "Boca Juniors", Position.DC, 77.0),
                // --- Racing Club ---
                new Player("Facundo Cambeses", "Racing Club", Position.ARQ, 76.0),
                new Player("Gabriel Rojas", "Racing Club", Position.LI, 75.0),
                new Player("Marco Di Cesare", "Racing Club", Position.DFC, 76.0),
                new Player("Agustín García Basso", "Racing Club", Position.DFC, 75.0),
                new Player("Gastón Martirena", "Racing Club", Position.LD, 76.0),
                new Player("Santiago Sosa", "Racing Club", Position.MC, 77.0),
                new Player("Gastón Lódico", "Racing Club", Position.MC, 75.0),
                new Player("Juan Fernando Quintero", "Racing Club", Position.MCO, 78.0),
                new Player("Santiago Solari", "Racing Club", Position.ED, 74.0),
                new Player("Johan Carbonero", "Racing Club", Position.EL, 75.0),
                new Player("Adrián 'Maravilla' Martínez", "Racing Club", Position.DC, 77.0),
                // --- Independiente ---
                new Player("Rodrigo Rey", "Independiente", Position.ARQ, 75.0),
                new Player("Facundo Zabala", "Independiente", Position.LI, 76.0),
                new Player("Kevin Lomónaco", "Independiente", Position.DFC, 74.0),
                new Player("Juan Fedorco", "Independiente", Position.DFC, 73.0),
                new Player("Leonardo Godoy", "Independiente", Position.LD, 73.0),
                new Player("Iván Marcone", "Independiente", Position.MC, 76.0),
                new Player("Maximiliano Meza", "Independiente", Position.MC, 73.0),
                new Player("Luciano Cabral", "Independiente", Position.MCO, 69.0),
                new Player("Santiago Montiel", "Independiente", Position.ED, 78.0),
                new Player("Matías Abaldo", "Independiente", Position.EL, 75.0),
                new Player("Gabriel Ávalos", "Independiente", Position.DC, 76.0),
                // --- Rosario Central ---
                new Player("Conan Ledesma", "Rosario Central", Position.ARQ, 76.0),
                new Player("Agustín Sández", "Rosario Central", Position.LI, 73.0),
                new Player("Carlos Quintana", "Rosario Central", Position.DFC, 74.0),
                new Player("Facundo Mallo", "Rosario Central", Position.DFC, 74.0),
                new Player("Emanuel Coronel", "Rosario Central", Position.LD, 73.0),
                new Player("Kevin Ortiz", "Rosario Central", Position.MC, 73.0),
                new Player("Franco Ibarra", "Rosario Central", Position.MC, 73.0),
                new Player("Ignacio Malcorra", "Rosario Central", Position.MCO, 75.0),
                new Player("Ángel Di María", "Rosario Central", Position.ED, 82.0),
                new Player("Jaminton Campaz", "Rosario Central", Position.EL, 76.0),
                new Player("Marco Ruben", "Rosario Central", Position.DC, 74.0),
                // --- Estudiantes LP ---
                new Player("Fernando Muslera", "Estudiantes LP", Position.ARQ, 78.0),
                new Player("Gastón Benedetti", "Estudiantes LP", Position.LI, 73.0),
                new Player("Facundo Rodríguez", "Estudiantes LP", Position.DFC, 74.0),
                new Player("Santiago Flores", "Estudiantes LP", Position.DFC, 72.0),
                new Player("Eric Meza", "Estudiantes LP", Position.LD, 74.0),
                new Player("Enzo Pérez", "Estudiantes LP", Position.MC, 75.0),
                new Player("Alexis Castro", "Estudiantes LP", Position.MC, 73.0),
                new Player("José Sosa", "Estudiantes LP", Position.MCO, 74.0),
                new Player("Tiago Palacios", "Estudiantes LP", Position.ED, 75.0),
                new Player("Edwuin Cetré", "Estudiantes LP", Position.EL, 76.0),
                new Player("Guido Carrillo", "Estudiantes LP", Position.DC, 76.0),
                // --- Vélez Sarsfield ---
                new Player("Tomás Marchiori", "Vélez Sarsfield", Position.ARQ, 75.0),
                new Player("Elías Gómez", "Vélez Sarsfield", Position.LI, 75.0),
                new Player("Emanuel Mammana", "Vélez Sarsfield", Position.DFC, 75.0),
                new Player("Patricio Pernicone", "Vélez Sarsfield", Position.DFC, 68.0),
                new Player("Joaquín García", "Vélez Sarsfield", Position.LD, 73.0),
                new Player("Claudio Baeza", "Vélez Sarsfield", Position.MC, 74.0),
                new Player("Lucas Robertone", "Vélez Sarsfield", Position.MC, 74.0),
                new Player("Manuel Lanzini", "Vélez Sarsfield", Position.MCO, 76.0),
                new Player("Matías Pellegrini", "Vélez Sarsfield", Position.ED, 73.0),
                new Player("Diego Valdés", "Vélez Sarsfield", Position.EL, 74.0),
                new Player("Braian Romero", "Vélez Sarsfield", Position.DC, 73.0),
                // --- Talleres de Córdoba ---
                new Player("Ezequiel Unsain", "Talleres de Córdoba", Position.ARQ, 75.0),
                new Player("Blas Riveros", "Talleres de Córdoba", Position.LI, 73.0),
                new Player("Matías Catalán", "Talleres de Córdoba", Position.DFC, 73.0),
                new Player("Lucas Suárez", "Talleres de Córdoba", Position.DFC, 72.0),
                new Player("Gastón Benavídez", "Talleres de Córdoba", Position.LD, 75.0),
                new Player("Federico Fattori", "Talleres de Córdoba", Position.MC, 77.0),
                new Player("Matías Galarza", "Talleres de Córdoba", Position.MC, 74.0),
                new Player("Franco Cristaldo", "Talleres de Córdoba", Position.MCO, 76.0),
                new Player("Diego Valoyes", "Talleres de Córdoba", Position.ED, 74.0),
                new Player("Valentín Depietri", "Talleres de Córdoba", Position.EL, 68.0),
                new Player("Federico Girotti", "Talleres de Córdoba", Position.DC, 75.0),
                // --- Belgrano de Córdoba ---
                new Player("Thiago Cardozo", "Belgrano de Córdoba", Position.ARQ, 74.0),
                new Player("Federico Ricca", "Belgrano de Córdoba", Position.LI, 72.0),
                new Player("Leonardo Morales", "Belgrano de Córdoba", Position.DFC, 74.0),
                new Player("Alexis Maldonado", "Belgrano de Córdoba", Position.DFC, 72.0),
                new Player("Gabriel Compagnucci", "Belgrano de Córdoba", Position.LD, 74.0),
                new Player("Adrián Sánchez", "Belgrano de Córdoba", Position.MC, 72.0),
                new Player("Franco Vázquez", "Belgrano de Córdoba", Position.MC, 75.0),
                new Player("Lucas Zelarayán", "Belgrano de Córdoba", Position.MCO, 80.0),
                new Player("Emiliano Rigoni", "Belgrano de Córdoba", Position.ED, 74.0),
                new Player("Bryan Reyna", "Belgrano de Córdoba", Position.EL, 75.0),
                new Player("Nicolás Fernández", "Belgrano de Córdoba", Position.DC, 77.0),
                // --- Lanús ---
                new Player("Nahuel Losada", "Lanús", Position.ARQ, 76.0),
                new Player("Sasha Marcich", "Lanús", Position.LI, 74.0),
                new Player("Carlos Izquierdoz", "Lanús", Position.DFC, 74.0),
                new Player("José Canale", "Lanús", Position.DFC, 72.0),
                new Player("Juan José Cáceres", "Lanús", Position.LD, 73.0),
                new Player("Agustín Cardozo", "Lanús", Position.MC, 72.0),
                new Player("Ramiro Carrera", "Lanús", Position.MC, 75.0),
                new Player("Marcelino Moreno", "Lanús", Position.MCO, 78.0),
                new Player("Eduardo Salvio", "Lanús", Position.ED, 74.0),
                new Player("Felipe Peña Biafore", "Lanús", Position.EL, 70.0),
                new Player("Walter Bou", "Lanús", Position.DC, 76.0),
                // --- San Lorenzo ---
                new Player("Orlando Gill", "San Lorenzo", Position.ARQ, 72.0),
                new Player("Malcom Braida", "San Lorenzo", Position.LI, 74.0),
                new Player("Gastón Hernández", "San Lorenzo", Position.DFC, 74.0),
                new Player("Jhohan Romaña", "San Lorenzo", Position.DFC, 74.0),
                new Player("Nicolás Tripichio", "San Lorenzo", Position.LD, 73.0),
                new Player("Gonzalo Abrego", "San Lorenzo", Position.MC, 72.0),
                new Player("Martín Río", "San Lorenzo", Position.MC, 72.0),
                new Player("Nahuel Barrios", "San Lorenzo", Position.MCO, 72.0),
                new Player("Ezequiel Cerutti", "San Lorenzo", Position.ED, 70.0),
                new Player("Matías Reali", "San Lorenzo", Position.EL, 73.0),
                new Player("Alexis Cuello", "San Lorenzo", Position.DC, 72.0),
                // --- Huracán ---
                new Player("Hernán Galíndez", "Huracán", Position.ARQ, 74.0),
                new Player("César Ibáñez", "Huracán", Position.LI, 70.0),
                new Player("Martín Nervo", "Huracán", Position.DFC, 73.0),
                new Player("Fabio Pereyra", "Huracán", Position.DFC, 72.0),
                new Player("Lucas Blondel", "Huracán", Position.LD, 71.0),
                new Player("Leonardo Gil", "Huracán", Position.MC, 72.0),
                new Player("Williams Alarcón", "Huracán", Position.MC, 75.0),
                new Player("Óscar Romero", "Huracán", Position.MCO, 73.0),
                new Player("Federico Vera", "Huracán", Position.ED, 70.0),
                new Player("Facundo Waller", "Huracán", Position.EL, 72.0),
                new Player("Ramón 'Wanchope' Ábila", "Huracán", Position.DC, 74.0),
                // --- Argentinos Juniors ---
                new Player("Brayan Cortés", "Argentinos Juniors", Position.ARQ, 74.0),
                new Player("Sebastián Prieto", "Argentinos Juniors", Position.LI, 72.0),
                new Player("Francisco Álvarez", "Argentinos Juniors", Position.DFC, 75.0),
                new Player("Erik Godoy", "Argentinos Juniors", Position.DFC, 71.0),
                new Player("Thiago Santamaría", "Argentinos Juniors", Position.LD, 73.0),
                new Player("Alan Lescano", "Argentinos Juniors", Position.MC, 77.0),
                new Player("Nicolás Oroz", "Argentinos Juniors", Position.MC, 74.0),
                new Player("Hernán López Muñoz", "Argentinos Juniors", Position.MCO, 75.0),
                new Player("Gastón Verón", "Argentinos Juniors", Position.ED, 69.0),
                new Player("Joaquín Gho", "Argentinos Juniors", Position.EL, 68.0),
                new Player("Tomás Molina", "Argentinos Juniors", Position.DC, 72.0),
                // --- Platense ---
                new Player("Juan Pablo Cozzani", "Platense", Position.ARQ, 73.0),
                new Player("Tomás Silva", "Platense", Position.LI, 69.0),
                new Player("Ignacio Vázquez", "Platense", Position.DFC, 74.0),
                new Player("Víctor Cuesta", "Platense", Position.DFC, 73.0),
                new Player("Juan Saborido", "Platense", Position.LD, 70.0),
                new Player("Maximiliano Amarfil", "Platense", Position.MC, 70.0),
                new Player("Leonel Picco", "Platense", Position.MC, 73.0),
                new Player("Franco Zapiola", "Platense", Position.MCO, 71.0),
                new Player("Guido Mainero", "Platense", Position.ED, 70.0),
                new Player("Gastón Togni", "Platense", Position.EL, 73.0),
                new Player("Nicolás 'Diente' López", "Platense", Position.DC, 74.0),
                // --- Defensa y Justicia ---
                new Player("Matías Borgogno", "Defensa y Justicia", Position.ARQ, 73.0),
                new Player("Fernando Román", "Defensa y Justicia", Position.LI, 68.0),
                new Player("David Martínez", "Defensa y Justicia", Position.DFC, 73.0),
                new Player("Damián Fernández", "Defensa y Justicia", Position.DFC, 71.0),
                new Player("Ezequiel Cannavo", "Defensa y Justicia", Position.LD, 70.0),
                new Player("Éver Banega", "Defensa y Justicia", Position.MC, 76.0),
                new Player("Aaron Molinas", "Defensa y Justicia", Position.MC, 74.0),
                new Player("David Barbona", "Defensa y Justicia", Position.MCO, 70.0),
                new Player("Julián López", "Defensa y Justicia", Position.ED, 70.0),
                new Player("Domingo Blanco", "Defensa y Justicia", Position.EL, 71.0),
                new Player("Leandro Fernández", "Defensa y Justicia", Position.DC, 68.0),
                // --- Atlético Tucumán ---
                new Player("Luis Ingolotti", "Atlético Tucumán", Position.ARQ, 69.0),
                new Player("Juan Infante", "Atlético Tucumán", Position.LI, 66.0),
                new Player("Juan Gabriel Rodríguez", "Atlético Tucumán", Position.DFC, 73.0),
                new Player("Gastón Suso", "Atlético Tucumán", Position.DFC, 72.0),
                new Player("Leonel Di Plácido", "Atlético Tucumán", Position.LD, 71.0),
                new Player("Kevin Ortiz", "Atlético Tucumán", Position.MC, 71.0),
                new Player("Guillermo Acosta", "Atlético Tucumán", Position.MC, 72.0),
                new Player("Martín Benítez", "Atlético Tucumán", Position.MCO, 72.0),
                new Player("Renzo Tesuri", "Atlético Tucumán", Position.ED, 71.0),
                new Player("Ramiro Ruiz Rodríguez", "Atlético Tucumán", Position.EL, 69.0),
                new Player("Leandro Díaz", "Atlético Tucumán", Position.DC, 74.0),
                // --- Unión de Santa Fe ---
                new Player("Matías Mansilla", "Unión de Santa Fe", Position.ARQ, 72.0),
                new Player("Bruno Pittón", "Unión de Santa Fe", Position.LI, 67.0),
                new Player("Juan Pablo Ludueña", "Unión de Santa Fe", Position.DFC, 68.0),
                new Player("Lautaro Vargas", "Unión de Santa Fe", Position.DFC, 71.0),
                new Player("Juan de Dios Pintado", "Unión de Santa Fe", Position.LD, 72.0),
                new Player("Víctor Ignacio Malcorra", "Unión de Santa Fe", Position.MC, 75.0),
                new Player("Mauro Pittón", "Unión de Santa Fe", Position.MC, 71.0),
                new Player("Augusto Solari", "Unión de Santa Fe", Position.MCO, 68.0),
                new Player("Julián Palacios", "Unión de Santa Fe", Position.ED, 73.0),
                new Player("Franco Fragapane", "Unión de Santa Fe", Position.EL, 69.0),
                new Player("Cristian Tarragona", "Unión de Santa Fe", Position.DC, 73.0),
                // --- Independiente Rivadavia ---
                new Player("Ezequiel Centurión", "Independiente Rivadavia", Position.ARQ, 71.0),
                new Player("Luciano Gómez", "Independiente Rivadavia", Position.LI, 72.0),
                new Player("Sheyko Studer", "Independiente Rivadavia", Position.DFC, 73.0),
                new Player("Leonard Costa", "Independiente Rivadavia", Position.DFC, 69.0),
                new Player("Alex Vigo", "Independiente Rivadavia", Position.LD, 70.0),
                new Player("José Florentín", "Independiente Rivadavia", Position.MC, 73.0),
                new Player("Franco Romero", "Independiente Rivadavia", Position.MC, 70.0),
                new Player("Leonel Bucca", "Independiente Rivadavia", Position.MCO, 70.0),
                new Player("Maximiliano Salas", "Independiente Rivadavia", Position.ED, 75.0),
                new Player("Gonzalo Ríos", "Independiente Rivadavia", Position.EL, 69.0),
                new Player("Alex Arce", "Independiente Rivadavia", Position.DC, 76.0),
                // --- Tigre ---
                new Player("Felipe Zenobio", "Tigre", Position.ARQ, 70.0),
                new Player("Federico Álvarez", "Tigre", Position.LI, 66.0),
                new Player("Joaquín Laso", "Tigre", Position.DFC, 71.0),
                new Player("Gian Nardelli", "Tigre", Position.DFC, 69.0),
                new Player("Guillermo Soto", "Tigre", Position.LD, 67.0),
                new Player("Jalil Elías", "Tigre", Position.MC, 71.0),
                new Player("Bruno Leyes", "Tigre", Position.MC, 70.0),
                new Player("Gonzalo Martínez", "Tigre", Position.MCO, 73.0),
                new Player("Jabes Saralegui", "Tigre", Position.ED, 70.0),
                new Player("Ian Subiabre", "Tigre", Position.EL, 71.0),
                new Player("Ignacio Russo", "Tigre", Position.DC, 71.0),
                // --- Instituto de Córdoba ---
                new Player("Marcos Ledesma", "Instituto de Córdoba", Position.ARQ, 70.0),
                new Player("Diego Sosa", "Instituto de Córdoba", Position.LI, 70.0),
                new Player("Jonathan Galván", "Instituto de Córdoba", Position.DFC, 70.0),
                new Player("Fernando Alarcón", "Instituto de Córdoba", Position.DFC, 68.0),
                new Player("Giuliano Cerato", "Instituto de Córdoba", Position.LD, 71.0),
                new Player("Franco Moyano", "Instituto de Córdoba", Position.MC, 68.0),
                new Player("Gastón Lodico", "Instituto de Córdoba", Position.MC, 72.0),
                new Player("Alex Luna", "Instituto de Córdoba", Position.MCO, 75.0),
                new Player("Jhon Córdoba", "Instituto de Córdoba", Position.ED, 70.0),
                new Player("Damián Puebla", "Instituto de Córdoba", Position.EL, 71.0),
                new Player("Facundo Suárez", "Instituto de Córdoba", Position.DC, 66.0),
                // --- Newell's Old Boys ---
                new Player("Gabriel Arias", "Newell's Old Boys", Position.ARQ, 73.0),
                new Player("Ángelo Martino", "Newell's Old Boys", Position.LI, 73.0),
                new Player("Lautaro Giannetti", "Newell's Old Boys", Position.DFC, 69.0),
                new Player("Ian Glavinovich", "Newell's Old Boys", Position.DFC, 68.0),
                new Player("Armando Méndez", "Newell's Old Boys", Position.LD, 70.0),
                new Player("Luca Regiardo", "Newell's Old Boys", Position.MC, 68.0),
                new Player("Rodrigo Fernández Cedrés", "Newell's Old Boys", Position.MC, 72.0),
                new Player("Mateo García", "Newell's Old Boys", Position.MCO, 69.0),
                new Player("Walter Mazzantti", "Newell's Old Boys", Position.ED, 69.0),
                new Player("Ramiro Sordo", "Newell's Old Boys", Position.EL, 72.0),
                new Player("Matías Cóccaro", "Newell's Old Boys", Position.DC, 70.0),
                // --- Central Córdoba (SdE) ---
                new Player("Alan Aguerre", "Central Córdoba (SdE)", Position.ARQ, 70.0),
                new Player("Leonardo Marchi", "Central Córdoba (SdE)", Position.LI, 65.0),
                new Player("Felipe Aguilar", "Central Córdoba (SdE)", Position.DFC, 71.0),
                new Player("Alejandro Maciel", "Central Córdoba (SdE)", Position.DFC, 69.0),
                new Player("Santiago Moyano", "Central Córdoba (SdE)", Position.LD, 66.0),
                new Player("Lucas González", "Central Córdoba (SdE)", Position.MC, 71.0),
                new Player("Cristian Vega", "Central Córdoba (SdE)", Position.MC, 69.0),
                new Player("Rodrigo Atencio", "Central Córdoba (SdE)", Position.MCO, 70.0),
                new Player("Leonardo Sequeira", "Central Córdoba (SdE)", Position.ED, 69.0),
                new Player("Horacio Tijanovich", "Central Córdoba (SdE)", Position.EL, 68.0),
                new Player("Michael Santos", "Central Córdoba (SdE)", Position.DC, 71.0),
                // --- Barracas Central ---
                new Player("Juan Espínola", "Barracas Central", Position.ARQ, 71.0),
                new Player("Rodrigo Insua", "Barracas Central", Position.LI, 72.0),
                new Player("Yonatthan Rak", "Barracas Central", Position.DFC, 70.0),
                new Player("Nicolás Demartini", "Barracas Central", Position.DFC, 68.0),
                new Player("Rafael Barrios", "Barracas Central", Position.LD, 69.0),
                new Player("Iván Tapia", "Barracas Central", Position.MC, 71.0),
                new Player("Yeison Gordillo", "Barracas Central", Position.MC, 66.0),
                new Player("Rodrigo Bogarín", "Barracas Central", Position.MCO, 68.0),
                new Player("Gonzalo Morales", "Barracas Central", Position.ED, 70.0),
                new Player("Nicolás Orsini", "Barracas Central", Position.EL, 69.0),
                new Player("Facundo Bruera", "Barracas Central", Position.DC, 70.0),
                // --- Gimnasia LP ---
                new Player("Nelson Insfrán", "Gimnasia LP", Position.ARQ, 74.0),
                new Player("Pedro Silva Torrejón", "Gimnasia LP", Position.LI, 68.0),
                new Player("Germán Conti", "Gimnasia LP", Position.DFC, 73.0),
                new Player("Enzo Martínez", "Gimnasia LP", Position.DFC, 72.0),
                new Player("Alexis Steimbach", "Gimnasia LP", Position.LD, 65.0),
                new Player("Ignacio Fernández", "Gimnasia LP", Position.MC, 75.0),
                new Player("Mateo Seoane", "Gimnasia LP", Position.MC, 67.0),
                new Player("Nicolás Barros Schelotto", "Gimnasia LP", Position.MCO, 66.0),
                new Player("Manuel Panaro", "Gimnasia LP", Position.ED, 66.0),
                new Player("Brian Andrada", "Gimnasia LP", Position.EL, 64.0),
                new Player("Jorge de Asís", "Gimnasia LP", Position.DC, 65.0),
                // --- Gimnasia y Esgrima (M) ---
                new Player("César Rigamonti", "Gimnasia y Esgrima (M)", Position.ARQ, 70.0),
                new Player("Facundo Lencioni", "Gimnasia y Esgrima (M)", Position.LI, 68.0),
                new Player("Ezequiel Muñoz", "Gimnasia y Esgrima (M)", Position.DFC, 72.0),
                new Player("Maximiliano Padilla", "Gimnasia y Esgrima (M)", Position.DFC, 66.0),
                new Player("Ismael Cortez", "Gimnasia y Esgrima (M)", Position.LD, 67.0),
                new Player("Tomás O'Connor", "Gimnasia y Esgrima (M)", Position.MC, 69.0),
                new Player("Ulises Sánchez", "Gimnasia y Esgrima (M)", Position.MC, 72.0),
                new Player("Tomás Ortíz", "Gimnasia y Esgrima (M)", Position.MCO, 67.0),
                new Player("Ignacio Sabatini", "Gimnasia y Esgrima (M)", Position.ED, 67.0),
                new Player("Matías Vargas", "Gimnasia y Esgrima (M)", Position.EL, 78.0),
                new Player("Santiago Rodríguez", "Gimnasia y Esgrima (M)", Position.DC, 69.0),
                // --- Banfield ---
                new Player("Diego Rodríguez", "Banfield", Position.ARQ, 73.0),
                new Player("Ignacio Abraham", "Banfield", Position.LI, 69.0),
                new Player("Nicolás Meriano", "Banfield", Position.DFC, 70.0),
                new Player("Nehuén Paz", "Banfield", Position.DFC, 70.0),
                new Player("Santiago López García", "Banfield", Position.LD, 70.0),
                new Player("Lautaro Ríos", "Banfield", Position.MC, 67.0),
                new Player("Yonathan Rodríguez", "Banfield", Position.MC, 70.0),
                new Player("Matías González", "Banfield", Position.MCO, 66.0),
                new Player("David Zalazar", "Banfield", Position.ED, 68.0),
                new Player("Tomás Adoryán", "Banfield", Position.EL, 67.0),
                new Player("Bruno Sepúlveda", "Banfield", Position.DC, 68.0),
                // --- Sarmiento de Junín ---
                new Player("Iván Mauricio Arboleda", "Sarmiento de Junín", Position.ARQ, 68.0),
                new Player("Gabriel Díaz Núñez", "Sarmiento de Junín", Position.LI, 68.0),
                new Player("Agustín Seyral", "Sarmiento de Junín", Position.DFC, 66.0),
                new Player("Juan Manuel Insaurralde", "Sarmiento de Junín", Position.DFC, 68.0),
                new Player("Juan Manuel Cabrera", "Sarmiento de Junín", Position.LD, 67.0),
                new Player("Cristian Zabala", "Sarmiento de Junín", Position.MC, 71.0),
                new Player("Mauricio Martínez", "Sarmiento de Junín", Position.MC, 71.0),
                new Player("Osmar Giménez", "Sarmiento de Junín", Position.MCO, 64.0),
                new Player("Joaquín Gho", "Sarmiento de Junín", Position.ED, 68.0),
                new Player("Nicolás Pasquini", "Sarmiento de Junín", Position.EL, 69.0),
                new Player("Junior Marabel", "Sarmiento de Junín", Position.DC, 70.0),
                // --- Deportivo Riestra ---
                new Player("Ignacio Arce", "Deportivo Riestra", Position.ARQ, 74.0),
                new Player("Rodrigo Gallo", "Deportivo Riestra", Position.LI, 64.0),
                new Player("Carlos Quintana", "Deportivo Riestra", Position.DFC, 74.0),
                new Player("Alan Barrionuevo", "Deportivo Riestra", Position.DFC, 67.0),
                new Player("Jonatan Goitia", "Deportivo Riestra", Position.LD, 67.0),
                new Player("Milton Céliz", "Deportivo Riestra", Position.MC, 67.0),
                new Player("Pablo Monje", "Deportivo Riestra", Position.MC, 66.0),
                new Player("Matías García", "Deportivo Riestra", Position.MCO, 66.0),
                new Player("Walter Acuña", "Deportivo Riestra", Position.ED, 66.0),
                new Player("Antony Alonso", "Deportivo Riestra", Position.EL, 67.0),
                new Player("Jonathan Herrera", "Deportivo Riestra", Position.DC, 68.0),
                // --- Aldosivi ---
                new Player("Sebastián Moyano", "Aldosivi", Position.ARQ, 69.0),
                new Player("Lucas Rodríguez", "Aldosivi", Position.LI, 65.0),
                new Player("Leonardo Sigali", "Aldosivi", Position.DFC, 72.0),
                new Player("Gonzalo Soto", "Aldosivi", Position.DFC, 66.0),
                new Player("Rodrigo González", "Aldosivi", Position.LD, 68.0),
                new Player("Alan Sosa", "Aldosivi", Position.MC, 65.0),
                new Player("Marcelo Esponda", "Aldosivi", Position.MC, 65.0),
                new Player("Valentín Larralde", "Aldosivi", Position.MCO, 65.0),
                new Player("Nicolás Laméndola", "Aldosivi", Position.ED, 65.0),
                new Player("Agustín Alonso", "Aldosivi", Position.EL, 65.0),
                new Player("Andrés Vombergar", "Aldosivi", Position.DC, 73.0),
                // --- Colón de Santa Fe ---
                new Player("Manuel Vicentini", "Colón de Santa Fe", Position.ARQ, 64.0),
                new Player("Facundo Castet", "Colón de Santa Fe", Position.LI, 65.0),
                new Player("Hernán Lópes", "Colón de Santa Fe", Position.DFC, 66.0),
                new Player("Paolo Goltz", "Colón de Santa Fe", Position.DFC, 66.0),
                new Player("Ezequiel Herrera", "Colón de Santa Fe", Position.LD, 66.0),
                new Player("Sebastián Prediger", "Colón de Santa Fe", Position.MC, 66.0),
                new Player("Nicolás Talpone", "Colón de Santa Fe", Position.MC, 66.0),
                new Player("Christian Bernardi", "Colón de Santa Fe", Position.MCO, 67.0),
                new Player("Federico Jourdan", "Colón de Santa Fe", Position.ED, 66.0),
                new Player("Ignacio Lago", "Colón de Santa Fe", Position.EL, 66.0),
                new Player("Javier Toledo", "Colón de Santa Fe", Position.DC, 66.0),
                // --- Estudiantes (RC) ---
                new Player("Lucas Bruera", "Estudiantes (RC)", Position.ARQ, 66.0),
                new Player("Ignacio Abraham", "Estudiantes (RC)", Position.LI, 65.0),
                new Player("Gonzalo Maffini", "Estudiantes (RC)", Position.DFC, 66.0),
                new Player("Marcio Gómez", "Estudiantes (RC)", Position.DFC, 65.0),
                new Player("Valentín Fenoglio", "Estudiantes (RC)", Position.LD, 65.0),
                new Player("Alejandro Cabrera", "Estudiantes (RC)", Position.MC, 68.0),
                new Player("Francisco Romero", "Estudiantes (RC)", Position.MC, 63.0),
                new Player("Tomás González", "Estudiantes (RC)", Position.MCO, 65.0),
                new Player("Nahuel Cainelli", "Estudiantes (RC)", Position.ED, 65.0),
                new Player("Mauro Valiente", "Estudiantes (RC)", Position.EL, 65.0),
                new Player("Yeison Moreno", "Estudiantes (RC)", Position.DC, 64.0),
                // --- Ferro Carril Oeste ---
                new Player("Mariano Monllor", "Ferro Carril Oeste", Position.ARQ, 65.0),
                new Player("Martín Rodríguez", "Ferro Carril Oeste", Position.LI, 64.0),
                new Player("Patricio Boolsen", "Ferro Carril Oeste", Position.DFC, 66.0),
                new Player("Gabriel Díaz", "Ferro Carril Oeste", Position.DFC, 65.0),
                new Player("Federico Murillo", "Ferro Carril Oeste", Position.LD, 65.0),
                new Player("Juan Fernandes Pinto", "Ferro Carril Oeste", Position.MC, 65.0),
                new Player("Nicolás Gómez", "Ferro Carril Oeste", Position.MC, 64.0),
                new Player("Ricardo Blanco", "Ferro Carril Oeste", Position.MCO, 66.0),
                new Player("Gastón Moreyra", "Ferro Carril Oeste", Position.ED, 65.0),
                new Player("Alexander Díaz", "Ferro Carril Oeste", Position.EL, 66.0),
                new Player("Mateo Levato", "Ferro Carril Oeste", Position.DC, 65.0)
        ));
    }

    
    public static List<Club> createClubPool() {
        return createClubs();
    }

    public static List<Player> createGoalkeeperPool() {
        List<Player> gks = new ArrayList<>();
        for (Player p : createStandardPlayers()) {
            if (p.getNativePosition() == Position.ARQ) {
                gks.add(p);
            }
        }
        return gks;
    }

    public static List<Player> createFieldPlayerPool() {
        List<Player> fps = new ArrayList<>();
        for (Player p : createStandardPlayers()) {
            if (p.getNativePosition() != Position.ARQ) {
                fps.add(p);
            }
        }
        return fps;
    }

    public static List<Player> createIdolPool() {
        return new ArrayList<>(Arrays.asList(
                new Player("Miguel Á. 'Pepé' Santoro", "Independiente", Position.ARQ, 82.0, PlayerRarity.LEYENDA),
                new Player("Amadeo Carrizo", "River Plate", Position.ARQ, 83.0, PlayerRarity.LEYENDA),
                new Player("Daniel Passarella", "River Plate", Position.DFC, 87.0, PlayerRarity.LEYENDA),
                new Player("Juan Román Riquelme", "Boca Juniors", Position.MCO, 90.0, PlayerRarity.LEYENDA),
                new Player("Ricardo Bochini", "Independiente", Position.MCO, 91.0, PlayerRarity.LEYENDA),
                new Player("Diego Milito", "Racing Club", Position.DC, 84.0, PlayerRarity.LEYENDA),
                new Player("Arsenio Erico", "Independiente", Position.DC, 85.0, PlayerRarity.LEYENDA),
                new Player("Mario Kempes", "Rosario Central", Position.DC, 86.0, PlayerRarity.LEYENDA),
                new Player("Carlos Tevez", "Boca Juniors", Position.DC, 88.0, PlayerRarity.LEYENDA),
                new Player("Gabriel Batistuta", "Boca Juniors", Position.DC, 89.0, PlayerRarity.LEYENDA)
        ));
    }
}